#!/bin/bash
# Uninstall Fldigi

set -euo pipefail
HAMAPPS_DIR="$(dirname "$(dirname "$(dirname "$(readlink -f "$0")")")")"
source "$HAMAPPS_DIR/scripts/utils"

info "Removing Fldigi..."
sudo apt-get remove -y fldigi
success "Fldigi removed."
