#!/bin/bash
# Install WSJT-X

set -euo pipefail
HAMAPPS_DIR="$(dirname "$(dirname "$(dirname "$(readlink -f "$0")")")")"
source "$HAMAPPS_DIR/scripts/utils"

info "Installing WSJT-X..."
sudo apt-get install -y wsjtx

success "WSJT-X installed."
