#!/bin/bash
# Uninstall WSJT-X

set -euo pipefail
HAMAPPS_DIR="$(dirname "$(dirname "$(dirname "$(readlink -f "$0")")")")"
source "$HAMAPPS_DIR/scripts/utils"

info "Removing WSJT-X..."
sudo apt-get remove -y wsjtx
mark_uninstalled wsjtx
success "WSJT-X removed."
